const subjectsData = [
  {
    id: 1,
    src: "./arabic.jpg",
    title: "Arabic",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    time: "Sun-Tue-Thu, 10:00 AM - 01:00 PM",
    time2: "Mon-Wed, 12:00 AM - 04:00 PM",
    ins: "Mr. Ahmad Omar",
    price: 60,
    max: 10,
  },
  {
    id: 2,
    src: "./english.jpg",
    title: "English",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    time: "Sun-Tue-Thu, 10:00 AM - 01:00 PM",
    time2: "Mon-Wed, 12:00 AM - 04:00 PM",
    ins: "Mr. Omar Khalid",
    price: 70,
    max: 10,
  },
  {
    id: 3,
    src: "./math.jpg",
    title: "Math",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    time: "Sun-Tue-Thu, 10:00 AM - 01:00 PM",
    time2: "Mon-Wed, 12:00 AM - 04:00 PM",
    ins: "Mr.Ibrahim Omar",
    price: 100,
    max: 15,
  },
  {
    id: 4,
    src: "./sc.jpg",
    title: "Science",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    time: "Sun-Tue-Thu, 10:00 AM - 01:00 PM",
    time2: "Mon-Wed, 12:00 AM - 04:00 PM",
    ins: "Mr.Ibrahim Omar",
    price: 90,
    max: 15,
  },
  {
    id: 5,
    src: "./physics2.jpg",
    title: "Physics",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    time: "Sun-Tue-Thu, 10:00 AM - 01:00 PM",
    time2: "Mon-Wed, 12:00 AM - 04:00 PM",
    ins: "Mr.Ibrahim Omar",
    price: 100,
    max: 20,
  },
  {
    id: 6,
    src: "./chemistry.jpg",
    title: "Chemistry",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    time: "Sun-Tue-Thu, 10:00 AM - 01:00 PM",
    time2: "Mon-Wed, 12:00 AM - 04:00 PM",
    ins: "Mr.Ibrahim Omar",
    price: 90,
    max: 10,
  },
  {
    id: 7,
    src: "./geology.jpg",
    title: "Geology",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    time: "Sun-Tue-Thu, 10:00 AM - 01:00 PM",
    time2: "Mon-Wed, 12:00 AM - 04:00 PM",
    ins: "Mr.Ibrahim Omar",
    price: 90,
    max: 10,
  },
  {
    id: 8,
    src: "./biology.jpg",
    title: "Biology",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    time: "Sun-Tue-Thu, 10:00 AM - 01:00 PM",
    time2: "Mon-Wed, 12:00 AM - 04:00 PM",
    ins: "Mr.Ibrahim Omar",
    price: 80,
    max: 15,
  },
  {
    id: 9,
    src: "./statistics.jpg",
    title: "Statistics",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    time: "Sun-Tue-Thu, 10:00 AM - 01:00 PM",
    time2: "Mon-Wed, 12:00 AM - 04:00 PM",
    ins: "Mr.Ibrahim Omar",
    price: 80,
    max: 15,
  },
];
export default subjectsData;
