const data = [
  {
    id: 1,
    src: "./subject/arabic.jpg",
    title: "Arabic",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    time: "Sun-Tue-Thu, 10:00 AM - 01:00 PM",
    ins: "Mr. Ahmad Omar",
  },
  {
    id: 2,
    src: "./subject/english.jpg",
    title: "English",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    time: "Sun-Tue-Thu, 10:00 AM - 01:00 PM",
    ins: "Mr. Omar Khalid",
  },
  {
    id: 3,
    src: "./subject/math.jpg",
    title: "Math",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    time: "Sun-Tue-Thu, 10:00 AM - 01:00 PM",
    ins: "Mr.Ibrahim Omar",
  },
  {
    id: 4,
    src: "./subject/sc.jpg",
    title: "Science",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    time: "Sun-Tue-Thu, 10:00 AM - 01:00 PM",
    ins: "Mr.Ibrahim Omar",
  },
  {
    id: 5,
    src: "./subject/physics2.jpg",
    title: "Physics",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    time: "Sun-Tue-Thu, 10:00 AM - 01:00 PM",
    ins: "Mr.Ibrahim Omar",
  },
  {
    id: 6,
    src: "./subject/chemistry.jpg",
    title: "Chemistry",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    time: "Sun-Tue-Thu, 10:00 AM - 01:00 PM",
    ins: "Mr.Ibrahim Omar",
  },
  {
    id: 7,
    src: "./subject/geology.jpg",
    title: "Geology",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    time: "Sun-Tue-Thu, 10:00 AM - 01:00 PM",
    ins: "Mr.Ibrahim Omar",
  },
  {
    id: 8,
    src: "./subject/biology.jpg",
    title: "Biology",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    time: "Sun-Tue-Thu, 10:00 AM - 01:00 PM",
    ins: "Mr.Ibrahim Omar",
  },
  {
    id: 9,
    src: "./subject/statistics.jpg",
    title: "Statistics",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    time: "Sun-Tue-Thu, 10:00 AM - 01:00 PM",
    ins: "Mr.Ibrahim Omar",
  },
];
export default data;
